apiVersion: v1
kind: Service
metadata:
  name: service-mp-wordpress
  labels:
    app: wordpress
spec:
  type : NodePort
  selector:
    app: wordpress
    tier: frontend
  ports:
    - port: 80
      nodePort : 30010